
services:

  nginx:
    container_name: nginx
    image: nginxinc/nginx-unprivileged:${DOCKER_IMAGE_TAG_NGINX}
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - type: bind
        source: ./services/nginx/configs/default.conf
        target: /tmp/default.conf
        read_only: true
      - type: bind
        source: ./services/nginx/bind_mounts/envsubst_default_conf.sh
        target: /docker-entrypoint.d/envsubst_default_conf.sh
        read_only: true
      - type: bind
        source: ./services/nginx/bind_mounts/index.html
        target: /usr/share/nginx/html/index.html
        read_only: true
      - type: bind
        source: ${CERTIFICATES_DIR}/${SERVER_CERTIFICATE}
        target: /etc/nginx/${SERVER_CERTIFICATE}
        read_only: true
      - type: bind
        source: ${CERTIFICATES_DIR}/${SERVER_CERTIFICATE_KEY}
        target: /etc/nginx/${SERVER_CERTIFICATE_KEY}
        read_only: true
    environment:
      - GITLAB_SUBDOMAIN_NAME=${GITLAB_SUBDOMAIN_NAME}
      - DEVOPS_DOMAIN_NAME=${DEVOPS_DOMAIN_NAME}
      - SERVER_CERTIFICATE=${SERVER_CERTIFICATE}
      - SERVER_CERTIFICATE_KEY=${SERVER_CERTIFICATE_KEY}
    extra_hosts:
      - '${GITLAB_SUBDOMAIN_NAME}.${DEVOPS_DOMAIN_NAME}:172.31.42.10'
    networks:
      - nginx-gitlab
    restart: always
    depends_on:
      gitlab:
        condition: service_started # service_started | service_healthy

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:${DOCKER_IMAGE_TAG_GITLAB}
    hostname: '${GITLAB_SUBDOMAIN_NAME}.${DEVOPS_DOMAIN_NAME}'
    ports:
      - '2222:22'
    expose:
      - '80'
      - '443'
    volumes:
      - type: bind
        source: ./services/gitlab/configs/gitlab.rb
        target: /etc/gitlab/gitlab.rb
        read_only: true
      - type: bind
        source: ./services/gitlab/bind_mounts/gitlab_pre_reconfigure_script.sh
        target: /tmp/gitlab_pre_reconfigure_script.sh
        read_only: true
      - type: bind
        source: ./services/gitlab/bind_mounts/gitlab_post_reconfigure_script.sh
        target: /tmp/gitlab_post_reconfigure_script.sh
        read_only: true
      - type: bind
        source: '${GITLAB_HOME}/config'
        target: '/etc/gitlab'
      - type: bind
        source: '${GITLAB_HOME}/logs'
        target: '/var/log/gitlab'
      - type: bind
        source: '${GITLAB_HOME}/data'
        target: '/var/opt/gitlab'
    environment:
      GITLAB_PRE_RECONFIGURE_SCRIPT: /tmp/gitlab_pre_reconfigure_script.sh
      GITLAB_POST_RECONFIGURE_SCRIPT: /tmp/gitlab_post_reconfigure_script.sh
      GITLAB_LOG_LEVEL: 'WARN'
      GITLAB_SKIP_TAIL_LOGS: 'true'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${GITLAB_SUBDOMAIN_NAME}.${DEVOPS_DOMAIN_NAME}'
        # Add any other gitlab.rb configuration here, each on its own line
    networks:
      nginx-gitlab:
        ipv4_address: 172.31.42.10
    shm_size: '256m' # shared memory size
    healthcheck:
      test: [ "CMD-SHELL", "/opt/gitlab/bin/gitlab-healthcheck --fail --max-time 10" ]
      interval: 1m0s
      timeout: 30s
      retries: 5
      start_period: 0s
#    restart: always

#  gitlab-runner:
#    container_name: gitlab-runner
#    image: gitlab/gitlab-runner:${DOCKER_IMAGE_TAG_GITLAB_RUNNER}

#  sonarqube:
#    container_name: sonarqube
#    image: sonarqube:${DOCKER_IMAGE_TAG_SONARQUBE}

#  jenkins:
#    container_name: jenkins
#    image: jenkins/jenkins:${DOCKER_IMAGE_TAG_JENKINS}

#  redmine:
#    container_name: redmine
#    image: redmine:${DOCKER_IMAGE_TAG_REDMINE}

#  postgres:
#    container_name: postgres
#    image: postgres:${DOCKER_IMAGE_TAG_POSTGRES}

networks:
  nginx-gitlab:
    ipam:
      driver: default
      config:
        - subnet: 172.31.42.0/24

