
version: '3.4'

services:

  nginx:
    container_name: nginx
    image: nginxinc/nginx-unprivileged:${DOCKER_IMAGE_TAG_NGINX}
    ports:
      - '8080:80'
      - '8443:443'
    secrets:
      - source: ssl_certificate
        target: /etc/nginx/${SERVER_CERTIFICATE}
        uid: '101'
        gid: '0'
        mode: 0444
      - source: ssl_certificate_key
        target: /etc/nginx/${SERVER_CERTIFICATE_KEY}
        uid: '101'
        gid: '0'
        mode: 0400
    configs:
      - source: nginx_default_conf_template
        target: /tmp/default.conf.template
        uid: '101'
        gid: '0'
        mode: 0444
      - source: nginx_envsubst_default_conf_template_sh
        target: /docker-entrypoint.d/envsubst_default_conf_template.sh
        uid: '101'
        gid: '0'
        mode: 0544
      - source: nginx_index_html
        target: /usr/share/nginx/html/index.html
        uid: '0'
        gid: '0'
        mode: 0444
    environment:
      - GITLAB_SUBDOMAIN_NAME=${GITLAB_SUBDOMAIN_NAME}
      - DEVOPS_DOMAIN_NAME=${DEVOPS_DOMAIN_NAME}
      - SERVER_CERTIFICATE=${SERVER_CERTIFICATE}
      - SERVER_CERTIFICATE_KEY=${SERVER_CERTIFICATE_KEY}
    networks:
      - nginx-gitlab
    restart: always
    depends_on:
      gitlab:
        condition: service_started # service_started | service_healthy

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:${DOCKER_IMAGE_TAG_GITLAB}
    hostname: '${GITLAB_SUBDOMAIN_NAME}.${DEVOPS_DOMAIN_NAME}'
    ports:
      - '2222:22'
    expose:
      - '80'
      - '443'
    configs:
      - source: gitlab_gitlab_rb
        target: /etc/gitlab/gitlab.rb
        uid: '0'
        gid: '0'
        mode: 0400
      - source: gitlab_gitlab_pre_reconfigure_script_sh
        target: /tmp/gitlab_pre_reconfigure_script.sh
        uid: '0'
        gid: '0'
        mode: 0544
      - source: gitlab_gitlab_post_reconfigure_script_sh
        target: /tmp/gitlab_post_reconfigure_script.sh
        uid: '0'
        gid: '0'
        mode: 0544
    volumes:
      - type: bind
        source: '${GITLAB_HOME}/config'
        target: '/etc/gitlab'
      - type: bind
        source: '${GITLAB_HOME}/logs'
        target: '/var/log/gitlab'
      - type: bind
        source: '${GITLAB_HOME}/data'
        target: '/var/opt/gitlab'
    environment:
      GITLAB_PRE_RECONFIGURE_SCRIPT: /tmp/gitlab_pre_reconfigure_script.sh
      GITLAB_POST_RECONFIGURE_SCRIPT: /tmp/gitlab_post_reconfigure_script.sh
      GITLAB_LOG_LEVEL: 'WARN'
      GITLAB_SKIP_TAIL_LOGS: 'true'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${GITLAB_SUBDOMAIN_NAME}.${DEVOPS_DOMAIN_NAME}'
        # Add any other gitlab.rb configuration here, each on its own line
    networks:
      - nginx-gitlab
    shm_size: '256m' # shared memory size
    healthcheck:
      test: [ "CMD-SHELL", "/opt/gitlab/bin/gitlab-healthcheck --fail --max-time 10" ]
      interval: 1m0s
      timeout: 30s
      retries: 5
      start_period: 0s
#    restart: always

#  gitlab-runner:
#    container_name: gitlab-runner
#    image: gitlab/gitlab-runner:${DOCKER_IMAGE_TAG_GITLAB_RUNNER}

#  sonarqube:
#    container_name: sonarqube
#    image: sonarqube:${DOCKER_IMAGE_TAG_SONARQUBE}

#  jenkins:
#    container_name: jenkins
#    image: jenkins/jenkins:${DOCKER_IMAGE_TAG_JENKINS}

#  redmine:
#    container_name: redmine
#    image: redmine:${DOCKER_IMAGE_TAG_REDMINE}

#  postgres:
#    container_name: postgres
#    image: postgres:${DOCKER_IMAGE_TAG_POSTGRES}

secrets:
  ssl_certificate:
    file: ${CERTIFICATES_DIR}/${SERVER_CERTIFICATE}
  ssl_certificate_key:
    file: ${CERTIFICATES_DIR}/${SERVER_CERTIFICATE_KEY}

configs:
  nginx_default_conf_template:
    file: ./services/nginx/configs/default.conf.template
  nginx_envsubst_default_conf_template_sh:
    file: ./services/nginx/configs/envsubst_default_conf_template.sh
  nginx_index_html:
    file: ./services/nginx/configs/index.html
  gitlab_gitlab_rb:
    file: ./services/gitlab/configs/gitlab.rb
  gitlab_gitlab_pre_reconfigure_script_sh:
    file: ./services/gitlab/configs/gitlab_pre_reconfigure_script.sh
  gitlab_gitlab_post_reconfigure_script_sh:
    file: ./services/gitlab/configs/gitlab_post_reconfigure_script.sh

networks:
  nginx-gitlab:

